### ISSUE TITLE
Should `Linear` layer include bias? 

### ISSUE THREAD

**Issue by benedict-96** [JuliaGNI/AbstractNeuralNetworks.jl#16]
In my opinion the linear layer https://github.com/JuliaGNI/AbstractNeuralNetworks.jl/blob/main/src/layers/linear.jl should not include a bias, as that would make it an *affine transformation*.

**Comment by michakraus** [comment]
Fixed by 1f2cd97a390c95ca03bca6dee0d3c340da715c65.
